/* profile picture id → local thumbnail. generated from ProfileList.json */
(function (root) {
  "use strict";
  var BY_KEY = {
    "3000001": "assets/icons/cookies/ch01.png",
    "3000002": "assets/icons/cookies/ch01.png",
    "3000003": "assets/icons/cookies/ch02.png",
    "3000004": "assets/icons/cookies/ch03.png",
    "3000005": "assets/icons/cookies/ch07.png",
    "3000006": "assets/icons/cookies/ch08.png",
    "3000007": "assets/icons/cookies/ch12.png",
    "3000008": "assets/icons/cookies/ch13.png",
    "3000009": "assets/icons/cookies/ch15.png",
    "3000010": "assets/icons/cookies/ch19.png",
    "3000011": "assets/icons/cookies/ch20.png",
    "3000012": "assets/icons/cookies/ch28.png",
    "3000013": "assets/icons/cookies/ch31.png",
    "3000014": "assets/icons/cookies/ch34.png",
    "3000015": "assets/icons/cookies/ch37.png",
    "3000016": "assets/icons/cookies/ch39.png",
    "3000017": "assets/icons/cookies/ch40.png",
    "3000018": "assets/icons/cookies/ch47.png",
    "3000019": "assets/icons/cookies/ch49.png",
    "3000020": "assets/icons/cookies/ch50.png",
    "3000021": "assets/icons/cookies/ch59.png",
    "3000022": "assets/icons/cookies/ch65.png",
    "3000023": "assets/icons/cookies/ch66.png",
    "3000024": "assets/icons/cookies/ch67.png",
    "3000025": "assets/icons/cookies/ch68.png",
    "3000026": "assets/icons/cookies/ch69.png",
    "3000027": "assets/icons/cookies/ch72.png",
    "3000028": "assets/icons/cookies/ch75.png",
    "3000029": "assets/icons/cookies/ch80.png",
    "3000030": "assets/icons/cookies/ch82.png",
    "3000031": "assets/icons/cookies/ch87.png",
    "3000032": "assets/icons/cookies/ch89.png",
    "3000033": "assets/icons/cookies/ch90.png",
    "3000034": "assets/icons/pets/pet01.png",
    "3000035": "assets/icons/pets/pet08.png",
    "3000036": "assets/icons/pets/pet100.png",
    "3000037": "assets/icons/pets/pet101.png",
    "3000038": "assets/icons/pets/pet19.png",
    "3000039": "assets/icons/pets/pet29.png",
    "3000040": "assets/icons/pets/pet37.png",
    "3000041": "assets/icons/pets/pet40.png",
    "3000042": "assets/icons/pets/pet47.png",
    "3000043": "assets/icons/pets/pet53.png",
    "3000044": "assets/icons/pets/pet56.png",
    "3000045": "assets/icons/pets/pet57.png",
    "3000046": "assets/icons/pets/pet67.png",
    "3000047": "assets/icons/pets/pet68.png",
    "3000048": "assets/icons/pets/pet69.png",
    "3000049": "assets/icons/pets/pet83.png",
    "3000050": "assets/icons/pets/pet87.png",
    "3000051": "assets/icons/pets/pet89.png",
    "3000052": "assets/icons/pets/pet90.png",
    "3000053": "assets/icons/pets/pet92.png",
    "3000054": "assets/icons/pets/pet94.png",
    "3000055": "assets/icons/pets/pet98.png",
    "3100001": "assets/icons/profiles/crc_event_profile_thumbnail_001.png",
    "3100002": "assets/icons/profiles/crc_event_profile_thumbnail_002.png",
    "3100003": "assets/icons/profiles/crc_event_profile_thumbnail_003.png",
    "3100004": "assets/icons/profiles/crc_event_profile_thumbnail_004.png",
    "3100005": "assets/icons/profiles/crc_event_profile_thumbnail_005.png",
    "3100006": "assets/icons/profiles/crc_event_profile_thumbnail_006.png",
    "3100007": "assets/icons/profiles/crc_event_profile_thumbnail_007.png",
    "3100008": "assets/icons/profiles/crc_event_profile_thumbnail_008.png",
    "3100009": "assets/icons/profiles/crc_event_profile_thumbnail_009.png",
    "3100010": "assets/icons/profiles/crc_event_profile_thumbnail_010.png",
    "3100011": "assets/icons/profiles/crc_event_profile_thumbnail_011.png",
    "3100012": "assets/icons/profiles/crc_event_profile_thumbnail_012.png",
    "3100013": "assets/icons/profiles/crc_event_profile_thumbnail_013.png",
    "3100014": "assets/icons/profiles/crc_event_profile_thumbnail_014.png",
    "3100015": "assets/icons/profiles/crc_event_profile_thumbnail_015.png",
    "3100016": "assets/icons/profiles/crc_event_profile_thumbnail_016.png",
    "3100017": "assets/icons/profiles/crc_event_profile_thumbnail_017.png",
    "3100018": "assets/icons/profiles/crc_event_profile_thumbnail_018.png",
    "3100019": "assets/icons/profiles/crc_event_profile_thumbnail_019.png",
    "3100020": "assets/icons/profiles/crc_event_profile_thumbnail_020.png",
    "3100021": "assets/icons/profiles/crc_event_profile_thumbnail_021.png",
    "3100022": "assets/icons/profiles/crc_event_profile_thumbnail_022.png",
    "crc_event_profile_thumbnail_001.png": "assets/icons/profiles/crc_event_profile_thumbnail_001.png",
    "crc_event_profile_thumbnail_002.png": "assets/icons/profiles/crc_event_profile_thumbnail_002.png",
    "crc_event_profile_thumbnail_003.png": "assets/icons/profiles/crc_event_profile_thumbnail_003.png",
    "crc_event_profile_thumbnail_004.png": "assets/icons/profiles/crc_event_profile_thumbnail_004.png",
    "crc_event_profile_thumbnail_005.png": "assets/icons/profiles/crc_event_profile_thumbnail_005.png",
    "crc_event_profile_thumbnail_006.png": "assets/icons/profiles/crc_event_profile_thumbnail_006.png",
    "crc_event_profile_thumbnail_007.png": "assets/icons/profiles/crc_event_profile_thumbnail_007.png",
    "crc_event_profile_thumbnail_008.png": "assets/icons/profiles/crc_event_profile_thumbnail_008.png",
    "crc_event_profile_thumbnail_009.png": "assets/icons/profiles/crc_event_profile_thumbnail_009.png",
    "crc_event_profile_thumbnail_010.png": "assets/icons/profiles/crc_event_profile_thumbnail_010.png",
    "crc_event_profile_thumbnail_011.png": "assets/icons/profiles/crc_event_profile_thumbnail_011.png",
    "crc_event_profile_thumbnail_012.png": "assets/icons/profiles/crc_event_profile_thumbnail_012.png",
    "crc_event_profile_thumbnail_013.png": "assets/icons/profiles/crc_event_profile_thumbnail_013.png",
    "crc_event_profile_thumbnail_014.png": "assets/icons/profiles/crc_event_profile_thumbnail_014.png",
    "crc_event_profile_thumbnail_015.png": "assets/icons/profiles/crc_event_profile_thumbnail_015.png",
    "crc_event_profile_thumbnail_016.png": "assets/icons/profiles/crc_event_profile_thumbnail_016.png",
    "crc_event_profile_thumbnail_017.png": "assets/icons/profiles/crc_event_profile_thumbnail_017.png",
    "crc_event_profile_thumbnail_018.png": "assets/icons/profiles/crc_event_profile_thumbnail_018.png",
    "crc_event_profile_thumbnail_019.png": "assets/icons/profiles/crc_event_profile_thumbnail_019.png",
    "crc_event_profile_thumbnail_020.png": "assets/icons/profiles/crc_event_profile_thumbnail_020.png",
    "crc_event_profile_thumbnail_021.png": "assets/icons/profiles/crc_event_profile_thumbnail_021.png",
    "crc_event_profile_thumbnail_022.png": "assets/icons/profiles/crc_event_profile_thumbnail_022.png",
    "crg_profile_thumbnail_ch01_1.png": "assets/icons/cookies/ch01.png",
    "crg_profile_thumbnail_ch01_2.png": "assets/icons/cookies/ch01.png",
    "crg_profile_thumbnail_ch02_1.png": "assets/icons/cookies/ch02.png",
    "crg_profile_thumbnail_ch03_1.png": "assets/icons/cookies/ch03.png",
    "crg_profile_thumbnail_ch07_1.png": "assets/icons/cookies/ch07.png",
    "crg_profile_thumbnail_ch08_1.png": "assets/icons/cookies/ch08.png",
    "crg_profile_thumbnail_ch12_1.png": "assets/icons/cookies/ch12.png",
    "crg_profile_thumbnail_ch13_1.png": "assets/icons/cookies/ch13.png",
    "crg_profile_thumbnail_ch15_1.png": "assets/icons/cookies/ch15.png",
    "crg_profile_thumbnail_ch19_1.png": "assets/icons/cookies/ch19.png",
    "crg_profile_thumbnail_ch20_1.png": "assets/icons/cookies/ch20.png",
    "crg_profile_thumbnail_ch28_1.png": "assets/icons/cookies/ch28.png",
    "crg_profile_thumbnail_ch31_1.png": "assets/icons/cookies/ch31.png",
    "crg_profile_thumbnail_ch34_1.png": "assets/icons/cookies/ch34.png",
    "crg_profile_thumbnail_ch37_1.png": "assets/icons/cookies/ch37.png",
    "crg_profile_thumbnail_ch39_1.png": "assets/icons/cookies/ch39.png",
    "crg_profile_thumbnail_ch40_1.png": "assets/icons/cookies/ch40.png",
    "crg_profile_thumbnail_ch47_1.png": "assets/icons/cookies/ch47.png",
    "crg_profile_thumbnail_ch49_1.png": "assets/icons/cookies/ch49.png",
    "crg_profile_thumbnail_ch50_1.png": "assets/icons/cookies/ch50.png",
    "crg_profile_thumbnail_ch59_1.png": "assets/icons/cookies/ch59.png",
    "crg_profile_thumbnail_ch65_1.png": "assets/icons/cookies/ch65.png",
    "crg_profile_thumbnail_ch66_1.png": "assets/icons/cookies/ch66.png",
    "crg_profile_thumbnail_ch67_1.png": "assets/icons/cookies/ch67.png",
    "crg_profile_thumbnail_ch68_1.png": "assets/icons/cookies/ch68.png",
    "crg_profile_thumbnail_ch69_1.png": "assets/icons/cookies/ch69.png",
    "crg_profile_thumbnail_ch72_1.png": "assets/icons/cookies/ch72.png",
    "crg_profile_thumbnail_ch75_1.png": "assets/icons/cookies/ch75.png",
    "crg_profile_thumbnail_ch80_1.png": "assets/icons/cookies/ch80.png",
    "crg_profile_thumbnail_ch82_1.png": "assets/icons/cookies/ch82.png",
    "crg_profile_thumbnail_ch87_1.png": "assets/icons/cookies/ch87.png",
    "crg_profile_thumbnail_ch89_1.png": "assets/icons/cookies/ch89.png",
    "crg_profile_thumbnail_ch90_1.png": "assets/icons/cookies/ch90.png",
    "crg_profile_thumbnail_pet01.png": "assets/icons/pets/pet01.png",
    "crg_profile_thumbnail_pet08.png": "assets/icons/pets/pet08.png",
    "crg_profile_thumbnail_pet100.png": "assets/icons/pets/pet100.png",
    "crg_profile_thumbnail_pet101.png": "assets/icons/pets/pet101.png",
    "crg_profile_thumbnail_pet19.png": "assets/icons/pets/pet19.png",
    "crg_profile_thumbnail_pet29.png": "assets/icons/pets/pet29.png",
    "crg_profile_thumbnail_pet37.png": "assets/icons/pets/pet37.png",
    "crg_profile_thumbnail_pet40.png": "assets/icons/pets/pet40.png",
    "crg_profile_thumbnail_pet47.png": "assets/icons/pets/pet47.png",
    "crg_profile_thumbnail_pet53.png": "assets/icons/pets/pet53.png",
    "crg_profile_thumbnail_pet56.png": "assets/icons/pets/pet56.png",
    "crg_profile_thumbnail_pet57.png": "assets/icons/pets/pet57.png",
    "crg_profile_thumbnail_pet67.png": "assets/icons/pets/pet67.png",
    "crg_profile_thumbnail_pet68.png": "assets/icons/pets/pet68.png",
    "crg_profile_thumbnail_pet69.png": "assets/icons/pets/pet69.png",
    "crg_profile_thumbnail_pet83.png": "assets/icons/pets/pet83.png",
    "crg_profile_thumbnail_pet87.png": "assets/icons/pets/pet87.png",
    "crg_profile_thumbnail_pet89.png": "assets/icons/pets/pet89.png",
    "crg_profile_thumbnail_pet90.png": "assets/icons/pets/pet90.png",
    "crg_profile_thumbnail_pet92.png": "assets/icons/pets/pet92.png",
    "crg_profile_thumbnail_pet94.png": "assets/icons/pets/pet94.png",
    "crg_profile_thumbnail_pet98.png": "assets/icons/pets/pet98.png",
  };
  function ckrProfilePortraitUrl(key) {
    var raw = String(key == null ? '' : key).trim();
    if (!raw || raw === '0') return '';
    var hit = BY_KEY[raw] || BY_KEY[raw.toLowerCase()];
    if (hit) return hit;
    var low = raw.toLowerCase();
    var cookie = low.match(/(?:^|_)(ch\d{2,3})(?:_|$|\.)/);
    if (cookie) return 'assets/icons/cookies/' + cookie[1] + '.png';
    var pet = low.match(/(?:^|_)(pet\d{1,3})(?:_|$|\.)/);
    if (pet) return 'assets/icons/pets/' + pet[1] + '.png';
    var event = low.match(/crc_event_profile_thumbnail_(\d+)/);
    if (event) {
      var n = event[1];
      while (n.length < 3) n = '0' + n;
      return 'assets/icons/profiles/crc_event_profile_thumbnail_' + n + '.png';
    }
    return '';
  }
  root.ckrProfilePortraitUrl = ckrProfilePortraitUrl;
})(typeof window !== 'undefined' ? window : globalThis);
